(function() {var implementors = {};
implementors["futures"] = [];implementors["tokio_core"] = ["impl&lt;T:&nbsp;<a class='trait' href='tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a>, C:&nbsp;<a class='trait' href='tokio_core/io/trait.Codec.html' title='tokio_core::io::Codec'>Codec</a>&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/io/struct.Framed.html' title='tokio_core::io::Framed'>Framed</a>&lt;T, C&gt;","impl&lt;T&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/channel/struct.Sender.html' title='tokio_core::channel::Sender'>Sender</a>&lt;T&gt;","impl&lt;C:&nbsp;<a class='trait' href='tokio_core/net/trait.UdpCodec.html' title='tokio_core::net::UdpCodec'>UdpCodec</a>&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/net/struct.UdpFramed.html' title='tokio_core::net::UdpFramed'>UdpFramed</a>&lt;C&gt;",];implementors["hyper"] = ["impl&lt;T, C&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/io/frame/struct.Framed.html' title='tokio_core::io::frame::Framed'>Framed</a>&lt;T, C&gt; <span class='where'>where C: <a class='trait' href='tokio_core/io/frame/trait.Codec.html' title='tokio_core::io::frame::Codec'>Codec</a>, T: <a class='trait' href='tokio_core/io/trait.Io.html' title='tokio_core::io::Io'>Io</a></span>","impl&lt;T&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/channel/struct.Sender.html' title='tokio_core::channel::Sender'>Sender</a>&lt;T&gt;","impl&lt;C&gt; <a class='trait' href='futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a> for <a class='struct' href='tokio_core/net/udp/frame/struct.UdpFramed.html' title='tokio_core::net::udp::frame::UdpFramed'>UdpFramed</a>&lt;C&gt; <span class='where'>where C: <a class='trait' href='tokio_core/net/udp/frame/trait.UdpCodec.html' title='tokio_core::net::udp::frame::UdpCodec'>UdpCodec</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
