[package]
name = "changes-stream"
description = "couchdb follower"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
license = "MIT"

[dependencies]
futures = "0.1.6"
tokio-core = "0.1.2"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
branch = "tokio"

[dependencies.hyper-tls]
git = "https://github.com/hyperium/hyper-tls.git"
