(function() {var implementors = {};
implementors["hyper"] = ["impl&lt;T, P&gt; <a class='trait' href='hyper/server/trait.Service.html' title='hyper::server::Service'>Service</a> for <a class='struct' href='tokio_proto/simple/pipeline/client/struct.ClientService.html' title='tokio_proto::simple::pipeline::client::ClientService'>ClientService</a>&lt;T, P&gt; <span class='where'>where P: <a class='trait' href='tokio_proto/simple/pipeline/client/trait.ClientProto.html' title='tokio_proto::simple::pipeline::client::ClientProto'>ClientProto</a>&lt;T&gt;, T: 'static</span>","impl&lt;T, P&gt; <a class='trait' href='hyper/server/trait.Service.html' title='hyper::server::Service'>Service</a> for <a class='struct' href='tokio_proto/simple/multiplex/client/struct.ClientService.html' title='tokio_proto::simple::multiplex::client::ClientService'>ClientService</a>&lt;T, P&gt; <span class='where'>where P: <a class='trait' href='tokio_proto/simple/multiplex/client/trait.ClientProto.html' title='tokio_proto::simple::multiplex::client::ClientProto'>ClientProto</a>&lt;T&gt;, T: 'static</span>","impl&lt;R, S, E&gt; <a class='trait' href='hyper/server/trait.Service.html' title='hyper::server::Service'>Service</a> for <a class='struct' href='tokio_proto/util/client_proxy/struct.ClientProxy.html' title='tokio_proto::util::client_proxy::ClientProxy'>ClientProxy</a>&lt;R, S, E&gt; <span class='where'>where E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt;</span>","impl <a class='trait' href='hyper/server/trait.Service.html' title='hyper::server::Service'>Service</a> for <a class='struct' href='hyper/client/struct.HttpConnector.html' title='hyper::client::HttpConnector'>HttpConnector</a>","impl&lt;C:&nbsp;<a class='trait' href='hyper/client/trait.Connect.html' title='hyper::client::Connect'>Connect</a>&gt; <a class='trait' href='hyper/server/trait.Service.html' title='hyper::server::Service'>Service</a> for <a class='struct' href='hyper/client/struct.Client.html' title='hyper::client::Client'>Client</a>&lt;C&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
